docs: Update image source URLs in README to reflect the correct repository name.

diff --git a/.github/workflows/tetris.yml b/.github/workflows/tetris.yml
--- a/.github/workflows/tetris.yml
+++ b/.github/workflows/tetris.yml
@@ -32,8 +32,8 @@ jobs:
 
       - name: Generate GIF
         run: |
-            python3 tetris/main.py --username abisinraj --theme light --output dist/github-contribution-grid-tetris.gif || { echo "Failed to generate light theme GIF"; exit 1; }
-            python3 tetris/main.py --username abisinraj --theme dark --output dist/github-contribution-grid-tetris-dark.gif || { echo "Failed to generate dark theme GIF"; exit 1; }
+            python3 tetris/main.py --username Abisin-Raj --theme light --output dist/github-contribution-grid-tetris.gif || { echo "Failed to generate light theme GIF"; exit 1; }
+            python3 tetris/main.py --username Abisin-Raj --theme dark --output dist/github-contribution-grid-tetris-dark.gif || { echo "Failed to generate dark theme GIF"; exit 1; }
         
       - name: Verify Generated Files
         run: |
